#exec once
exec-once = qs
exec-once = awww-daemon
# #exec allways
# exec = bash ~/.config/mango/reload-settings.sh

#keybinds
bind = SUPER, Q, killclient
bind = SUPER, T, spawn, foot
bind = SUPER, R, reload_config
bind = SUPER,Tab,toggleoverview
bind = SUPER, G, switch_layout
bind = SUPER, F, togglefloating
bind = SUPER, W, spawn, firefox
bind = SUPER, E, spawn, nautilus
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +10%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 10%-
bind=,XF86AudioRaiseVolume,spawn, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind=,XF86AudioLowerVolume,spawn,wpctl set-sink-volume @DEFAULT_SINK@ 5%-
bind=,XF86AudioMute,spawn,pactl set-sink-mute @DEFAULT_SINK@ toggle


#workspaces
bind = SUPER, 1,view,1
bind = SUPER, 2,view,2
bind = SUPER, 3,view,3
bind = SUPER, 4,view,4
bind = SUPER, 5,view,5
bind = SUPER, 6,view,6
bind = SUPER, 7,view,7
bind = SUPER, 8,view,8
bind = SUPER, 9,view,9

#settings

borderpx=0
circle_layout=dwindle,tile,right_tile,center_tile,grid

#mousebinds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

#tags
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle
tagrule=id:10,layout_name:dwindle
